// Dummy data so the UI has something to render.
// Later this should come from a real API call (see src/services/tripService.js
// for the pattern used elsewhere in this app) — swap PACKAGES for that response.

export const PACKAGES = [
  {
    id: 1,
    title: "Leh Ladakh Adventure",
    badge: "Best Seller",
    theme: "Adventure",
    destination: "Ladakh",
    location: "Leh, Nubra Valley, Pangong Lake",
    days: 5,
    nights: 4,
    includes: ["Meals", "Stay", "Transport", "Guide"],
    rating: 4.8,
    reviews: 512,
    price: 14999,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 2,
    title: "Goa Beach Holiday",
    badge: "Popular",
    theme: "Beach",
    destination: "Goa",
    location: "North Goa, South Goa",
    days: 4,
    nights: 3,
    includes: ["Meals", "Stay", "Transport"],
    rating: 4.6,
    reviews: 387,
    price: 8999,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 3,
    title: "Kedarnath Yatra",
    badge: "Trending",
    theme: "Spiritual",
    destination: "Uttarakhand",
    location: "Kedarnath",
    days: 3,
    nights: 2,
    includes: ["Stay", "Meals", "Transport", "Guide"],
    rating: 4.9,
    reviews: 842,
    price: 6999,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 4,
    title: "Bali Exotic Escape",
    badge: "New",
    theme: "Honeymoon",
    destination: "Bali",
    location: "Ubud, Seminyak, Nusa Penida",
    days: 6,
    nights: 5,
    includes: ["Meals", "Stay", "Transport", "Visa"],
    rating: 4.7,
    reviews: 221,
    price: 39999,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1573790387438-4da905039392?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 5,
    title: "Munnar Nature Retreat",
    badge: null,
    theme: "Family",
    destination: "Kerala",
    location: "Munnar, Kerala",
    days: 3,
    nights: 2,
    includes: ["Meals", "Stay", "Transport"],
    rating: 4.5,
    reviews: 164,
    price: 7649,
    originalPrice: 8999,
    image: "https://images.unsplash.com/photo-1598091383021-15ddea10925d?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 6,
    title: "Manali Weekend Trip",
    badge: null,
    theme: "Weekend Getaway",
    destination: "Himachal Pradesh",
    location: "Manali, Himachal Pradesh",
    days: 3,
    nights: 2,
    includes: ["Stay", "Transport"],
    rating: 4.4,
    reviews: 298,
    price: 5599,
    originalPrice: 6999,
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 7,
    title: "Rajasthan Heritage Tour",
    badge: null,
    theme: "Luxury",
    destination: "Rajasthan",
    location: "Jaipur, Udaipur, Jodhpur",
    days: 5,
    nights: 4,
    includes: ["Meals", "Stay", "Transport", "Guide"],
    rating: 4.7,
    reviews: 356,
    price: 17999,
    originalPrice: 19999,
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94245?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: 8,
    title: "Varanasi Spiritual Journey",
    badge: null,
    theme: "Spiritual",
    destination: "Uttarakhand",
    location: "Varanasi",
    days: 3,
    nights: 2,
    includes: ["Stay", "Meals", "Guide"],
    rating: 4.6,
    reviews: 201,
    price: 6159,
    originalPrice: 6999,
    image: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?q=80&w=600&auto=format&fit=crop",
  },
]